# Generated by Django 6.0.5 on 2026-05-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siglas', '0002_student_delete_students'),
    ]

    operations = [
    ]
