# Generated by Django 6.0.5 on 2026-05-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siglas', '0004_auto_20260528_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False, 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursesstudents',
            options={'managed': False, 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
