# Generated by Django 6.0.5 on 2026-06-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siglas', '0005_alter_courses_options_alter_coursesstudents_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': True, 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursesstudents',
            options={'managed': True, 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True, 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True, 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
